-- Discord bridge: account linking. See docs/architecture.md "Discord bridge & admin chat".

CREATE TABLE rigel_discord_links (
    uuid            VARCHAR(36) NOT NULL PRIMARY KEY,
    discord_user_id VARCHAR(32) NOT NULL,
    linked_at       BIGINT      NOT NULL
);

CREATE INDEX idx_discord_links_discord_user ON rigel_discord_links (discord_user_id);

-- Short-lived one-time codes generated by /discord link and consumed via a DM to the
-- bot ("!link <code>") - never posted in a public/admin channel, only DMs.
CREATE TABLE rigel_discord_link_codes (
    code       VARCHAR(16) NOT NULL PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    created_at BIGINT      NOT NULL,
    expires_at BIGINT      NOT NULL
);
