package org.rigelmc.identity;

/**
 * The kind of client identity a connecting player has, relevant on this server's
 * topology (single Paper backend behind Velocity, bridging Bedrock via GeyserMC/Floodgate
 * and browser/cracked clients via an Eaglercraft-compatible proxy plugin).
 *
 * <p>See the "Network topology & multi-client identity" section of the project's
 * architecture plan for why this distinction matters: {@link #OFFLINE} identities have
 * UUIDs trivially regenerated by picking a new username, which is why ban enforcement
 * for that identity type is IP-primary rather than UUID-primary.</p>
 */
public enum PlayerIdentity {

    /** A real premium Mojang account (Java Edition, online-mode). */
    JAVA,

    /** A Bedrock Edition player bridged in via GeyserMC/Floodgate. */
    BEDROCK,

    /**
     * An offline-mode identity: either a cracked Java client, or a browser/Eaglercraft
     * client bridged in via the proxy. UUID is {@code UUID.nameUUIDFromBytes(...)} derived
     * from the username and is not a durable identifier - see the ban system design.
     */
    OFFLINE
}
