package org.rigelmc.punish.ban;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.rigelmc.api.event.RigelPlayerBannedEvent.BanType;
import org.rigelmc.audit.AuditLogService;
import org.rigelmc.data.dao.IpHistoryDao;
import org.rigelmc.data.dao.PlayerDao;
import org.rigelmc.data.dao.PlayerRecord;

/**
 * The ban system's core logic - see docs/architecture.md "Ban system: /ban, /tban,
 * /permban cascade, flags, web panel" for the full design. Pure JDBC + plain Java (no
 * Bukkit types): CoreProtect rollback triggering and in-game messaging are the command
 * layer's job ({@code punish.PunishModule}), not this service's - keeps this class
 * unit-testable without a live server, see {@code BanServiceTest}.
 */
public final class BanService {

    private final BanDao banDao;
    private final PlayerDao playerDao;
    private final IpHistoryDao ipHistoryDao;
    private final AuditLogService auditLogService;

    public BanService(
            @NotNull BanDao banDao,
            @NotNull PlayerDao playerDao,
            @NotNull IpHistoryDao ipHistoryDao,
            @NotNull AuditLogService auditLogService) {
        this.banDao = banDao;
        this.playerDao = playerDao;
        this.ipHistoryDao = ipHistoryDao;
        this.auditLogService = auditLogService;
    }

    /**
     * {@code /ban} - fixed-duration quick ban. Duration is decided by the caller
     * (config-driven, default 24h - see {@code RigelConfig#banDefaultDuration}); the
     * mandatory CoreProtect rollback this command always triggers is the command layer's
     * responsibility, not this method's.
     */
    @NotNull
    public Ban banByName(
            @NotNull UUID targetUuid,
            @NotNull String targetName,
            @NotNull String reason,
            @Nullable UUID actorUuid,
            long nowEpochMillis,
            long expiresAtEpochMillis)
            throws SQLException {
        Ban ban = banDao.insert(new Ban(
                0,
                null,
                BanType.NAME_TEMP,
                targetUuid,
                targetName,
                null,
                reason,
                actorUuid,
                nowEpochMillis,
                expiresAtEpochMillis,
                true,
                null,
                null));
        auditLogService.record(actorUuid, "BAN", targetUuid, reason);
        return ban;
    }

    /**
     * {@code /ban}/{@code /gtfo} - user-requested: bans the name AND the target's current
     * (or, if offline, most-recently-seen) IP together, not just the name - a real, if
     * lighter-weight, evasion gap {@code /ban} alone had, since an offline/Eaglercraft
     * identity is trivially regenerated by picking a new username (same reasoning
     * {@link #permban}'s own cascade exists for, just single-IP and temp-duration rather
     * than full-history and permanent). Both rows share one {@code caseId} so {@code
     * /punish unban -c} can lift them together, same mechanism {@link #permban} already
     * uses - {@code /punish unban <name>} (no flag) still only lifts the name entry.
     *
     * @param targetIpHash the IP to ban alongside the name, already hashed by the caller
     *     (this service never sees a raw IP, matching {@link #permban}'s own convention) -
     *     or {@code null} if no IP could be resolved for this target (e.g. banning a name
     *     that has never actually connected), in which case this behaves exactly like
     *     {@link #banByName} and no {@code caseId}/IP row is created at all
     */
    @NotNull
    public List<Ban> banByNameAndIp(
            @NotNull UUID targetUuid,
            @NotNull String targetName,
            @Nullable String targetIpHash,
            @NotNull String reason,
            @Nullable UUID actorUuid,
            long nowEpochMillis,
            long expiresAtEpochMillis)
            throws SQLException {
        String caseId = targetIpHash != null ? UUID.randomUUID().toString() : null;
        List<Ban> created = new ArrayList<>();
        created.add(banDao.insert(new Ban(
                0, caseId, BanType.NAME_TEMP, targetUuid, targetName, null, reason, actorUuid, nowEpochMillis,
                expiresAtEpochMillis, true, null, null)));
        if (targetIpHash != null) {
            created.add(banDao.insert(new Ban(
                    0, caseId, BanType.IP_TEMP, null, null, targetIpHash, reason, actorUuid, nowEpochMillis,
                    expiresAtEpochMillis, true, null, null)));
        }
        auditLogService.record(
                actorUuid, "BAN", targetUuid,
                reason + (targetIpHash != null ? " (name + IP)" : " (name only - no known IP)"));
        return created;
    }

    /**
     * {@code /permban <name|ip>} - permanent ban with cascading identity resolution.
     * Given a name, resolves every IP that UUID has ever logged in from and bans them
     * all together; given an IP, resolves every UUID that has ever logged in from it and
     * bans them all together. All entries share one {@code caseId} so they can be viewed
     * or lifted as a unit. See docs/architecture.md's ban-evasion rationale: offline/
     * Eaglercraft UUIDs are trivially regenerated by picking a new username, so this
     * cascade is the actual anti-evasion mechanism, not just a convenience.
     *
     * @param input either a player name or an IP address (see {@link IpAddressUtil})
     * @param inputIpHash pre-hashed form of {@code input}, only used when {@code input}
     *     is an IP address - callers hash with {@link org.rigelmc.identity.IpHasher}
     *     before calling, since hashing needs the install-specific salt this pure-JDBC
     *     service deliberately doesn't own
     * @return every ban entry created by this cascade, in creation order
     */
    @NotNull
    public List<Ban> permban(
            @NotNull String input,
            @Nullable String inputIpHash,
            @NotNull String reason,
            @Nullable UUID actorUuid,
            long nowEpochMillis)
            throws SQLException {
        String caseId = UUID.randomUUID().toString();
        List<Ban> created = new ArrayList<>();

        if (IpAddressUtil.looksLikeIp(input)) {
            if (inputIpHash == null) {
                throw new IllegalArgumentException("inputIpHash is required when input looks like an IP");
            }
            created.add(insertLinked(caseId, BanType.IP_PERM, null, null, inputIpHash, reason, actorUuid, nowEpochMillis));
            for (UUID uuid : ipHistoryDao.findUuidsForIp(inputIpHash)) {
                String name = playerDao.findByUuid(uuid).map(PlayerRecord::lastKnownName).orElse(null);
                created.add(insertLinked(caseId, BanType.NAME_PERM, uuid, name, null, reason, actorUuid, nowEpochMillis));
            }
        } else {
            Optional<PlayerRecord> player = playerDao.findByLastKnownName(input);
            UUID uuid = player.map(PlayerRecord::uuid).orElse(null);
            created.add(insertLinked(caseId, BanType.NAME_PERM, uuid, input, null, reason, actorUuid, nowEpochMillis));

            if (uuid != null) {
                for (String ipHash : ipHistoryDao.findIpsForUuid(uuid)) {
                    created.add(
                            insertLinked(caseId, BanType.IP_PERM, null, null, ipHash, reason, actorUuid, nowEpochMillis));
                }
            }
        }

        auditLogService.record(
                actorUuid, "PERMBAN", null, "cascade case=" + caseId + " input=" + input + " entries=" + created.size()
                        + " reason=" + reason);
        return created;
    }

    /** {@code /tban} - explicit-duration temp ban, no cascade. */
    @NotNull
    public Ban tempBanByName(
            @NotNull UUID targetUuid,
            @NotNull String targetName,
            @NotNull String reason,
            @Nullable UUID actorUuid,
            long nowEpochMillis,
            long expiresAtEpochMillis)
            throws SQLException {
        Ban ban = banDao.insert(new Ban(
                0,
                null,
                BanType.NAME_TEMP,
                targetUuid,
                targetName,
                null,
                reason,
                actorUuid,
                nowEpochMillis,
                expiresAtEpochMillis,
                true,
                null,
                null));
        auditLogService.record(actorUuid, "TBAN", targetUuid, reason);
        return ban;
    }

    /**
     * {@code /punish unban <name|ip>}. Single-entry by default; pass {@code wholeCase =
     * true} (the {@code -c}/{@code --case} flag) to lift every entry in the cascade case
     * this ban belongs to instead, so unbanning one shared-IP housemate doesn't silently
     * unban everyone else caught by the same cascade.
     *
     * @return the number of ban entries lifted (0 means "wasn't banned", not an error -
     *     mirrors the defensive-on-empty-result design used throughout this service)
     */
    public int unban(@NotNull String input, @Nullable String inputIpHash, boolean wholeCase, @Nullable UUID actorUuid, long nowEpochMillis)
            throws SQLException {
        long now = nowEpochMillis;
        Optional<Ban> active;
        if (IpAddressUtil.looksLikeIp(input)) {
            if (inputIpHash == null) {
                throw new IllegalArgumentException("inputIpHash is required when input looks like an IP");
            }
            active = banDao.findActiveByIp(inputIpHash, now);
        } else {
            Optional<PlayerRecord> player = playerDao.findByLastKnownName(input);
            if (player.isEmpty()) {
                return 0;
            }
            active = banDao.findActiveByUuid(player.get().uuid(), now);
        }

        if (active.isEmpty()) {
            return 0;
        }

        Ban ban = active.get();
        int revoked;
        if (wholeCase && ban.caseId() != null) {
            revoked = banDao.revokeCase(ban.caseId(), actorUuid, now);
        } else if (ban.targetUuid() != null) {
            revoked = banDao.revokeByUuid(ban.targetUuid(), actorUuid, now);
        } else if (ban.targetIpHash() != null) {
            revoked = banDao.revokeByIp(ban.targetIpHash(), actorUuid, now);
        } else {
            banDao.revoke(ban.id(), actorUuid, now);
            revoked = 1;
        }
        auditLogService.record(actorUuid, "UNBAN", ban.targetUuid(), "input=" + input + " wholeCase=" + wholeCase);
        return revoked;
    }

    public boolean isBanned(@NotNull UUID uuid, long nowEpochMillis) throws SQLException {
        return banDao.findActiveByUuid(uuid, nowEpochMillis).isPresent();
    }

    public boolean isIpBanned(@NotNull String ipHash, long nowEpochMillis) throws SQLException {
        return banDao.findActiveByIp(ipHash, nowEpochMillis).isPresent();
    }

    /**
     * @return this player's full ban history (active, expired, and revoked alike), most
     *     recent first, capped at {@code limit} - for {@code /banhistory} (Moderator+, see
     *     {@code punish.PunishModule}).
     */
    @NotNull
    public List<Ban> history(@NotNull UUID uuid, int limit) throws SQLException {
        return banDao.findHistoryByUuid(uuid, limit);
    }

    private Ban insertLinked(
            String caseId,
            BanType type,
            UUID targetUuid,
            String targetName,
            String targetIpHash,
            String reason,
            UUID actorUuid,
            long nowEpochMillis)
            throws SQLException {
        return banDao.insert(new Ban(
                0, caseId, type, targetUuid, targetName, targetIpHash, reason, actorUuid, nowEpochMillis, null, true,
                null, null));
    }
}
